### ISSUE TITLE
Plugin fails to load when unconfigured on EDMC 5.0.0

### ISSUE THREAD

**Issue by cmachikas** [anthonylangsworth/FCMS#1]
`2021-05-15 22:23:38.851 - DEBUG - 4604:20440:20440 plugins.edsm.plugin_start3:149: Starting worker thread...
2021-05-15 22:23:38.853 - DEBUG - 4604:11960:11960 plugins.edsm.worker:521: Starting...
2021-05-15 22:23:38.853 - DEBUG - 4604:20440:20440 plugins.edsm.plugin_start3:153: Done.
2021-05-15 22:23:38.854 - INFO - 4604:20440:20440 plug.Plugin.__init__:49: loading plugin "edsy" from "C:\Program Files (x86)\EDMarketConnector\plugins\edsy.py"
2021-05-15 22:23:38.855 - INFO - 4604:20440:20440 plug.Plugin.__init__:49: loading plugin "inara" from "C:\Program Files (x86)\EDMarketConnector\plugins\inara.py"
2021-05-15 22:23:38.863 - DEBUG - 4604:20440:20440 plugins.inara.plugin_start3:171: Starting worker thread...
2021-05-15 22:23:38.864 - DEBUG - 4604:16160:16160 plugins.inara.new_worker:1233: Starting...
2021-05-15 22:23:38.865 - DEBUG - 4604:20440:20440 plugins.inara.plugin_start3:175: Done.
2021-05-15 22:23:38.865 - INFO - 4604:20440:20440 plug.Plugin.__init__:49: loading plugin "FCMS" from "C:\Users\cmach\AppData\Local\EDMarketConnector\plugins\FCMS\load.py"
2021-05-15 22:23:38.867 - ERROR - 4604:20440:20440 plug.Plugin.__init__:64: : Failed for Plugin "FCMS"
Traceback (most recent call last):
  File "plug.pyc", line 55, in __init__
  File "C:\Users\cmach\AppData\Local\EDMarketConnector\plugins\FCMS\load.py", line 43, in plugin_start3
    config.delete("FCMSEmail")
  File "config.pyc", line 610, in delete
FileNotFoundError: [WinError 2] The system cannot find the file specified
2021-05-15 22:23:38.869 - ERROR - 4604:20440:20440 plug.load_plugins:161: Failure loading found Plugin "FCMS"
Traceback (most recent call last):
  File "plug.pyc", line 159, in load_plugins
  File "plug.pyc", line 55, in __init__
  File "C:\Users\cmach\AppData\Local\EDMarketConnector\plugins\FCMS\load.py", line 43, in plugin_start3
    config.delete("FCMSEmail")
  File "config.pyc", line 610, in delete
FileNotFoundError: [WinError 2] The system cannot find the file specified
2021-05-15 22:23:38.912 - DEBUG - 4604:20440:20440 monitor.EDLogs.start:166: Begin...
2021-05-15 22:23:38.914 - DEBUG - 4604:20440:20440 monitor.EDLogs.start:209: Not polling, no observer, starting an observer...
2021-05-15 22:23:38.915 - DEBUG - 4604:20440:20440 monitor.EDLogs.start:213: Done`

When running EDMC 5.0.0 and FCMS 0.9 without prior configuration, FCMS will fail to load. 

Solution was downgrading both EDMC to 4.2.7 and FCMS to 0.7, configuring the 3 fields in the FCMS tab, then upgrading in place. Without, the FCMS plugin fails to load on boot, with both Release 0.7 and 0.9.

**Comment by anthonylangsworth** [comment]
Thanks for the bug report. I am trialling a fix. I hope to have it out in the next day or so.

**Comment by anthonylangsworth** [comment]
I released a new version that fixes the issue (v0.10). Please verify whether this has fixed your issue, @cmachikas .

**Comment by cmachikas** [comment]
Purged my EDMC config, and was able to install 0.10 and load as normal. Thanks for the fix!
